version: '3'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - flask-app

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
